[profile.default]
src = "src"
out = "out"
remappings = [
    '@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    '@openzeppelin/=lib/openzeppelin-contracts/contracts/',
    '@onchain-id/=lib/solidity/contracts/'
]
libs = ["node_modules", "lib"]

[fmt]
line_length = 120

[doc]
include = ['src']
output = "docs"

[profile.test]
verbosity = 2
ffi = true

[invariant]
runs = 256
depth = 15

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[compiler]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200
evm_version = "paris"
