const fs = require('fs');
const path = require('path');

// List of main contracts to generate ABIs for
const contracts = [
  'OwnmaliFactory',
  'OwnmaliSPV',
  'OwnmaliAsset',
  'OwnmaliAssetManager',
  'OwnmaliOrderManager',
  'OwnmaliFinancialLedger',
  'OwnmaliDAO',
  'OwnmaliRegistry'
];

// Create abis directory if it doesn't exist
const abisDir = path.join(__dirname, 'abis');
if (!fs.existsSync(abisDir)) {
  fs.mkdirSync(abisDir, { recursive: true });
}

// Compile contract and extract ABI
function generateABI(contractName) {
  console.log(`Generating ABI for ${contractName}...`);
  
  try {
    // Get the contract's artifact (generated by Hardhat/Foundry)
    const artifactPath = path.join(__dirname, 'out', `${contractName}.sol`, `${contractName}.json`);
    
    if (fs.existsSync(artifactPath)) {
      const artifact = JSON.parse(fs.readFileSync(artifactPath, 'utf8'));
      const abi = JSON.stringify(artifact.abi, null, 2);
      
      // Save ABI to file
      const outputPath = path.join(abisDir, `${contractName}.json`);
      fs.writeFileSync(outputPath, abi);
      
      console.log(`  ✓ ABI saved to ${outputPath}`);
      return true;
    } else {
      console.log(`  ⚠️  Artifact not found for ${contractName}`);
      return false;
    }
  } catch (error) {
    console.error(`  ✗ Error generating ABI for ${contractName}:`, error.message);
    return false;
  }
}

// Generate ABIs for all contracts
console.log('Generating ABIs for Ownmali contracts...\n');

let successCount = 0;
contracts.forEach(contract => {
  if (generateABI(contract)) {
    successCount++;
  }
});

console.log(`\nABI generation complete. Successfully generated ${successCount} of ${contracts.length} ABIs.`);
