name: CI/CD - 1xfinance API

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # lets us push to GHCR with GITHUB_TOKEN
    permissions:
      contents: read
      packages: write

    env:
      TAG: main

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute lowercase image name
        id: vars
        shell: bash
        run: |
          echo "image_lc=ghcr.io/${GITHUB_REPOSITORY,,}" >> "$GITHUB_OUTPUT"
          echo "image_mixed=ghcr.io/${GITHUB_REPOSITORY}" >> "$GITHUB_OUTPUT"

      - name: Log in to GHCR (using built-in token)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image to GHCR (lowercase + mixed-case)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ steps.vars.outputs.image_lc }}:${{ env.TAG }}
            ${{ steps.vars.outputs.image_lc }}:${{ github.sha }}
            ${{ steps.vars.outputs.image_mixed }}:${{ env.TAG }}
            ${{ steps.vars.outputs.image_mixed }}:${{ github.sha }}

      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT || 22 }}
          script_stop: true
          script: |
            set -euo pipefail
            cd /opt/1xfinance-api
            # (Optional) if your GHCR package is PRIVATE, uncomment these 2 lines and set EC2_GHCR_USER/EC2_GHCR_TOKEN secrets
            # echo "${{ secrets.EC2_GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.EC2_GHCR_USER }}" --password-stdin
            # echo "Logged into GHCR on EC2"

            # Pull the newly built image
            docker compose pull
            docker compose up -d

            # Health check (public https)
            for i in {1..24}; do
              code=$(curl -sk -o /dev/null -w "%{http_code}" https://api.1xfinance.com/health)
              if [ "$code" = "200" ]; then
                echo "Health OK"
                exit 0
              fi
              sleep 5
            done
            echo "Health check failed" >&2
            exit 1
