name: CI/CD - 1xfinance API

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      TAG: main

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Preflight: ensure required repository secrets exist
      - name: Preflight secrets check
        shell: bash
        run: |
          missing=0
          for k in EC2_HOST EC2_USER EC2_SSH_KEY; do
            v="${{ secrets.EC2_HOST }}"; if [ "$k" = EC2_USER ]; then v="${{ secrets.EC2_USER }}"; fi
            if [ "$k" = EC2_SSH_KEY ]; then v="${{ secrets.EC2_SSH_KEY }}"; fi
            if [ -z "$v" ]; then
              echo "::error::Missing required secret: $k"
              missing=1
            fi
          done
          if [ "$missing" -ne 0 ]; then exit 1; fi

      - name: Compute lowercase image name
        id: vars
        shell: bash
        run: echo "image_lc=ghcr.io/${GITHUB_REPOSITORY,,}" >> "$GITHUB_OUTPUT"

      - name: Log in to GHCR (built-in token)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image (lowercase only)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ steps.vars.outputs.image_lc }}:${{ env.TAG }}
            ${{ steps.vars.outputs.image_lc }}:${{ github.sha }}

      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT || 22 }}
          script_stop: true
          script: |
            set -euo pipefail
            cd /opt/1xfinance-api
            docker compose pull
            docker compose up -d

            # Health check (public)
            for i in {1..24}; do
              code=$(curl -sk -o /dev/null -w "%{http_code}" https://api.1xfinance.com/health)
              if [ "$code" = "200" ]; then
                echo "Health OK"
                exit 0
              fi
              sleep 5
            done
            echo "Health check failed" >&2
            exit 1
